spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://172.16.230.59:5432/health_care?currentSchema=notification
    username: superadmin
    password: admin@123
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      idle-timeout: 60000
      connection-timeout: 30000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    allow-bean-definition-overriding: true
  config:
    import: kafka.yml
  mail:
    host: smtp.gmail.com
    port: 587
    username: ulka.drc@gmail.com
    password: lhgkzktqsfnrrkxe
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
      debug: false

management:
  endpoint:
    health:
      probes:
        enabled: true

server:
  tomcat:
    URI-encoding: UTF-8
  port: 8091
  shutdown: graceful # Service port

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Eureka server URL
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost  # Optional: specify the hostname
    prefer-ip-address: true

service:
  mode: dummy

otp:
  bad-odt-limit: 10
  temp-block-in-minute: 10
  length: 4
  isHash: false
  salt: 789654123
  otp-validity-in-minute: 10

